POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video node",
  "description": "Esse é o primeiro video",
  "duration": 180
}


### 

GET http://localhost:3333/videos


###

PUT http://localhost:3333/videos/0923b688-0247-42ed-b5ff-39fbc83d72cc
Content-Type: application/json

{
  "title": "Video 01",
  "description": "Esse é o primeiro video",
  "duration": 180
}


###

DELETE http://localhost:3333/videos/6ece2bdc-af6e-4114-8785-8aaf42dd19c4
Content-Type: application/json